/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
import com.phidget22.*;

DigitalOutput redLED;

void initialize(){
  
  try{
    redLED = new DigitalOutput();    
    redLED.setHubPort(1);
    redLED.setIsHubPortDevice(true);
    redLED.open(1000);
    
  }catch(Exception e){
   
    e.printStackTrace();
  }
  
  redLED.addAttachListener(new AttachListener() {
    
    @Override
    public void onAttach(AttachEvent e) {

      button1.setEnabled(true);

    }
  });

  
  redLED.addDetachListener(new DetachListener() {
    @Override
    public void onDetach(DetachEvent e) {
      
      button1.setEnabled(false);

    }

  }); 

    try{
    redLED.open();
      }catch (Exception e2) {
          // TODO Auto-generated catch block
          e2.printStackTrace();
        }

  }
  
public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:458130:
          try {
          buttonClick();
        } catch (Exception e) {
          // TODO Auto-generated catch block
          e.printStackTrace();
        }
} //_CODE_:button1:458130:

private void buttonClick()throws Exception{
  
      if (redLED.getState())
      button1.setText("LED On");
    else
      button1.setText("LED Off");

    redLED.setState(!redLED.getState());
    
}



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 190, 140, 80, 30);
  button1.setText("LED On");
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
